<section class= "connexion container">
    <form action="index.php?action=authentificationAdmin" method="post" >
        <label for="email">Identifiant</label><input type="email" name="email" id="email" placeholder="Saisir votre identifiant"/>
        <label for="password">Mot de passe</label><input type="password" name="password" id="password" placeholder="Saisir votre mot de passe"/>
        <button type="submit">Login</button>
    </form>
</section>