<?php
$this->adminController=new AdminController();
if(!$this->adminController->is_connect()):
header("location:index.php");
endif; ?>

<section class="admin_update_article container"> 
    <h2>Modifier l'article </h2>
    <form action="index.php?action=updateArticle&id=<?=$lastArticle["id"]?>" enctype="multipart/form-data" method="post">
        <label for="titre"> Titre : </label><input type="text" name="titre" value="<?=$lastArticle['title']?>" id="titre" />
        <label for="contenu">Article :</label><textarea rows="4" cols="20" name ="contenu" id="contenu" placeholder="Veuillez saisir votre article"><?=$lastArticle['content']?></textarea>
        <label for="image"> Image : </label><input type="file" name="image" id="image" value="<?=$lastArticle['picture']?>"/>
        <div class="buttons">
            <button type="submit" class="btn">Mettre à jour</button>
            <button type="reset" class="btn">Réinitialiser les champs</button>
        </div>
    </form>
</section>