<section class="contact container">
    <h3>Utilisez le formulaire de contact pour toute question, suggestion ou remarque</h3>
    <form action="index.php?action=askContact" method="post" id="form_Contact">
            <label for="nom">Nom / Pseudo</label><input type="text" name="nom" id="nom" placeholder="Saisir votre nom / pseudo">
            <label for="message">Message</label><textarea rows="5" cols="20" name="message" id="message" placeholder="Saisir votre message"></textarea>
            <button type="submit" value="Envoyer" id="send_Contact">Envoyer</button>
    </form>
</section>