<section class="about container"> 
    <section>
        <h2>À propos de moi</h2>
        <div>
            <img src="view/img/about/about-1.jpg" alt="Image d'illustrations">
        </div>
        <p>
            A la suite d'une reconversion professionnelle, j'ai décidé de me tourner vers les métiers du web l'année dernière.
            Ce secteur d'activité étant en constante évolution, et la demande de nouveaux développeurs étant continue, 
            il constitue un secteur très attrayant.
        </p>
        <p>
            Le métier de développeur bougeant constamment, étant donné le nombre de languages de programation existant, 
            la formation d'un développeur ne se termine jamais vraiment. Il est toujours possible d'apprendre de nouveaux langages et 
            d'acquérir de nouvelles compétences.
        </p>
    </section>
    <blockquote>
        <p>
            <i class="fas fa-quote-right"></i> Codez toujours comme si la personne qui allait maintenir votre code était un violent psychopathe qui sait où vous habitez. <i class="fas fa-quote-left"></i>
        </p>
        <footer>- John Woods</footer>
    </blockquote>    
    <section>
        <h2>Pourquoi ce site ?</h2>
        <p>
            J'ai réalisé ce site dans le cadre de la formation "Développeur - Intégrateur web en réalisation d'application web" que j'ai effectuée à la <strong><a href="https://3wa.fr/">3W Academy</a></strong> à Paris.
        </p>
        <div class="logo3WA">
            <a href="https://3wa.fr/"><img src="view/img/about/about-2.png" alt="Logo de la 3W Academy"></a>
        </div>
        <p>
            Cette formation m'a permis d'acquérir des connaissances en HTML, CSS, Javascript, PHP et MySQL. Ce site est mon projet de fin de formation, qui vise à mettre 
            en pratique les notions vues dans les différents langages au cours de la formation.
        </p>
        <div class="languages">
            <img src="view/img/about/logo_html.png" alt="Logo HTML">
            <img src="view/img/about/logo_css.png" alt="Logo CSS">
            <img src="view/img/about/logo_javascript.png" alt="Logo Javascript">
            <img src="view/img/about/logo_php.png" alt="Logo PHP">
            <img src="view/img/about/logo_sql.png" alt="Logo MySQL">
        </div>
        <p>
            Le sujet du projet de fin de formation étant libre, j'ai voulu créer un site en rapport avec une de mes passions.
            C'est pour cela que j'ai décidé de réaliser ce site sur le club de foot de Liverpool, équipe que je supporte depuis que je suis enfant, et que j'ai eu 
            l'occasion d'aller voir jouer au stade.        
        </p>
    </section>
</section>
     