<section class="home container">
    <article class="home-club-presentation"> 
        <h2>LE LIVERPOOL FOOTBALL CLUB</h2>
        <div class="info-presentation">
            <div class="picture">        
                <img src="view/img/home/home-1.jpg" alt="Vue des supporters de Liverpool"/>
                <figcaption>Les supporters de Liverpool dans le stade.</figcaption>
            </div>
            <div class="presentation-content">
                <p>
                    Le Liverpool Football Club a été fondé en 1892. Il est installé dans la ville de Liverpool, dans le nord-ouest de l'Angleterre.
                    L'emblème de l'équipe est le Liver Bird, qui est aussi l'emblème de la ville.
                    L'équipe évolue dans le stade d'Anfield.
                </p>
                <p>
                    Ses supporters sont parmi les plus réputés à l'échelle mondiale, notamment grâce à leur hymne : le You'll Never Walk Alone,
                    chant connu par les supporters du monde entier.            
                </p>
            </div>
        </div>
    </article>
    <article class="home-club-palmares"> 
        <h2>PALMARÈS DE L'ÉQUIPE</h2>
        <div class="info-presentation">
            <div class="picture">
                <img src="view/img/home/home-2.jpg" alt="Les trophées remportés par le club ces deux dernières années" />
                <figcaption>Les trophées remportés par le club ces deux dernières années (de gauche à droite : la Supercoupe d'Europe, la Ligue des Champions, le championnat d'Angleterre, la coupe du monde ces clubs) .</figcaption>
            </div>
            <div class="presentation-content">
                <p>
                    Liverpool possède le plus beau palmarès d'Angleterre, et aussi un des plus impressionnants d'Europe.
                    Le club a notamment remporté 19 titres de champions d'Angleterre, le dernier ayant été remporté cette année, 
                    et 6 Ligues des Champions, le trophée le plus prestigieux qu'un club de football puisse remporter.
                </p>
                <p>
                    Le meilleur buteur de l'histoire du club est Ian Rush, légende du club, qui a inscrit 
                    346 buts durant son passage au club entre 1980 et 1996. C'est aussi lui qui détient le record du 
                    plus grand nombre de buts inscrits lors d'une seule saison : 47 buts toutes compétitions confondues en 1983/1984.
                </p>
                <p>
                    Le joueur ayant le record de matchs disputés avec l'équipe est Ian Callaghan, avec 857 matchs disputés 
                    entre 1958 et 1978.
                </p>
            </div>
        </div>
        <ul class="ul-1">
            <li><h3>Au niveau national</h3>
                <ul>
                    <li>Championnat d'Angleterre : 19 victoires</li>
                    <li>FA Cup : 7 victoires</li>
                    <li>League Cup : 8 victoires</li>
                    <li>Community Shield : 15 victoires</li>
                </ul>
            </li>
            <li><h3>Au niveau européen</h3>
                <ul>
                    <li>Ligue des Champions : 6 victoires</li>
                    <li>Coupe UEFA / Europa League : 3 victoires</li>
                    <li>Supercoupe de l'UEFA : 4 victoires</li>
                </ul>
            </li>
            <li><h3>Au niveau mondial</h3>
                <ul>
                    <li>Coupe du monde des clubs : 1 victoire</li>
                </ul>
            </li>
        </ul>
    </article>
    <article class="home-players">
        <h2>LES JOUEURS</h2>        
        <div class="info-presentation">
            <div class="picture">
                <img src="view/img/home/home-3.jpg" alt="Les joueurs célébrant le titre de champions d'Angleterre"/>
                <figcaption>Les joueurs après avoir reçu le trophée de champions d'Angleterre.</figcaption>    
            </div>
            <div class="presentation-content">
                <p>
                    Le club s'est cette année appuyé sur un effectif professionnel composé de 24 joueurs.
                    Tous ont eu un rôle à jouer dans l'excellente saison réalisée par l'équipe cette année, du capitaine Jordan Henderson à Sadio Mané, 
                    en passant par Alisson Becker, Trent Alexander-Arnold ou bien Bobby Firmino.
                </p>
                <p>
                    Les meilleurs buteurs cette saison ont été Mohamed Salah et Sadio Mané, qui ont inscrit 23 et 22 buts toutes compétitions confondues.
                    Le joueur avec le plus de passes décisives est Trent Alexander-Arnold avec un total de 15 passes ayant conduit à un but.
                    Il est difficile de désigner le meilleur joueur de la saison, tant chacun d'entre eux à une forte importance dans le système de Jürgen Klopp.
                </p>
            </div>
        </div>
        <ul class="ul-1">
            <li><h3>Les gardiens</h3>
                <ul>
                    <li>Alisson Becker</li>
                    <li>Adrián</li>
                    <li>Caoimhin Kelleher</li>
                </ul>
            </li>
            <li><h3>Les défenseurs</h3>
                <ul>
                    <li>Virgil Van Dijk</li>
                    <li>Joe Gomez</li>
                    <li>Andrew Robertson</li>
                    <li>Joël Matip</li>
                    <li>Ki-Jana Hoever</li>
                    <li>Trent Alexander-Arnold</li>
                    <li>Dejan Lovren</li>
                </ul>
            </li>
            <li><h3>Les milieux de terrain</h3>
                <ul>
                    <li>Fabinho</li>
                    <li>Georginio Wijnaldum</li>
                    <li>James Milner</li>
                    <li>Naby Keita</li>
                    <li>Jordan Henderson</li>
                    <li>Alex Oxlade-Chamberlain</li>
                    <li>Takumi Minamino</li>
                    <li>Xherdan Shaqiri</li>
                    <li>Curtis Jones</li>
                    <li>Harvey Elliott</li>
                </ul>
            </li>
            <li><h3>Les attaquants</h3>
                <ul>
                    <li>Roberto Firmino</li>
                    <li>Sadio Mané</li>
                    <li>Mohamed Salah</li>
                    <li>Divock Origi</li>
                </ul>
            </li>
        </ul>
    </article>
    <article class="home-staff">
        <h2>LE STAFF</h2>
        <div class="info-presentation">
            <div class="picture">
                <img src="view/img/home/home-4.jpg" alt="Jurgen Klopp entouré de ses adjoints"/>
                <figcaption>Jürgen Klopp au centre, entouré de Peter Krawietz (à gauche) et de Pepijn Lijnders (à droite).</figcaption>
            </div>
            <div class="presentation-content">
                <p>
                    Ceux sans qui rien n'aurait été possible : 
                    Jürgen Klopp et ses adjoints Pepijn Lijnders et Peter Krawietz.
                </p>
                <p>
                    Le coach allemand a très largement contribué à ramener le club sur le devant de la scène 
                    depuis son arrivée au club en octobre 2015.
                    Avant lui, l'équipe n'avait plus obtenu de bons résultats depuis de trop longues années.
                    Il a su refaire du LFC une équipe qui compte et qui est crainte par ses adveraires.
                    Il est l'entraineur qui aura réussi à faire gagner un titre de champion d'Angleterre, 
                    chose qui n'était plus arrivée depuis 1990.
                </p>
            </div>
        </div>
    </article>
</section>    